import React from "react";
import { IoStatsChartOutline } from "react-icons/io5";

type Props = {
  isOpen: boolean;
  onClose: () => void;
};

const AdminPlatformReport: React.FC<Props> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div
      id="admin-report"
      className="fixed inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center z-50"
    >
      <div className="bg-white shadow-xl rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto relative p-8 border">
        {/* Close */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 text-2xl"
        >
          ✕
        </button>

        {/* Header */}
        <h1 className="text-xl font-semibold mb-1">T2Drive - Platform Report</h1>
        <p className="text-sm text-gray-500 mb-4">
          Period: 01 – 03 Nov 2025 • Generated by Finance
        </p>

        {/* Icon */}
        <div className="flex items-center gap-2 mb-4">
          <IoStatsChartOutline className="text-2xl text-indigo-600" />
          <h2 className="text-lg font-medium">Financial Summary</h2>
        </div>

        <div className="border-t" />

        {/* Summary */}
        <div className="py-4 text-sm space-y-3">
          <div className="flex justify-between">
            <span className="text-gray-600">Total Rides</span>
            <span className="font-semibold">562</span>
          </div>

          <div className="flex justify-between">
            <span className="text-gray-600">Gross Earnings</span>
            <span className="font-semibold">₹1,25,400.00</span>
          </div>

          <div className="flex justify-between">
            <span className="text-gray-600">Taxes Collected</span>
            <span className="font-semibold">₹6,270.00</span>
          </div>

          <div className="flex justify-between">
            <span className="text-gray-600">Net Revenue</span>
            <span className="font-semibold">₹1,31,670.00</span>
          </div>

          <div className="flex justify-between">
            <span className="text-gray-600">Commission (20%)</span>
            <span className="font-semibold">₹25,080.00</span>
          </div>

          <div className="flex justify-between">
            <span className="text-gray-600">Driver Payouts</span>
            <span className="font-semibold">₹1,00,320.00</span>
          </div>

          <div className="flex justify-between">
            <span className="text-gray-600">Platform Incentives</span>
            <span className="font-semibold">₹3,000.00</span>
          </div>

          <div className="border-t my-3"></div>

          {/* Net Profit */}
          <div className="flex justify-between text-base font-semibold">
            <span>Net Profit</span>
            <span>₹26,334.00</span>
          </div>

          <div className="flex justify-between text-sm mt-2">
            <span className="text-gray-600">Total GST Collected</span>
            <span className="font-medium">₹7,524.00</span>
          </div>
        </div>

        <div className="border-t mt-6" />

        <p className="text-center text-gray-500 text-sm mt-4 mb-2">Verified by Finance Lead</p>
      </div>
    </div>
  );
};

export default AdminPlatformReport;
